import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const gentyRegular = localFont({
	src: [
		{
			path: './fonts/GentyDemo-Regular.otf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-genty-regular',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${gentyRegular.className}`}>{children}</body>
		</html>
	);
}
